### ISSUE TITLE
question about makim clean

### ISSUE THREAD

**Issue by libialany** [osl-incubator/makim#6]
* makim version: latest
* Python version: Python 3.10.6:
* Operating System: Ubuntu 22.04.1
 
### Description

I executed the command makim clean
It raised an error : Traceback

### What I Did

```
makim clean
Traceback (most recent call last):
  File "/home/nora/mambaforge/envs/makim/bin/makim", line 6, in <module>
    sys.exit(app())
  File "/home/nora/Downloads/makim/makim/__main__.py", line 129, in app
    return makim.run(dict(args._get_kwargs()))
  File "/home/nora/Downloads/makim/makim/makim.py", line 160, in run
    self._load_target_data()
  File "/home/nora/Downloads/makim/makim/makim.py", line 86, in _load_target_data
    self.target_data = self.group_data['targets'][self.target_name]
KeyError: 'clean'
```
I need to add arguments to `makim clean` command.

**Comment by xmnlab** [comment]
thanks for reporting this!
could you share with us the content of your .makim.yaml file pls?

**Comment by xmnlab** [comment]
are you using it on a specific project? or are you running it from a makim  repo?

**Comment by xmnlab** [comment]
this should be working also with a custom makimfile path. thanks
